#Cleaning Data

First, let's take a look at our raw data

In [1]:
import pandas as pd
plrty = pd.read_csv("Polarity_rawData_50.csv")
plrty.head()

,id,Title,Text,Reads,Likes,Shares,Hearts,Date Published
0,1,Interview: Struggles in Learning English and H...,Interview: Struggles in Learning English and H...,198,12,10,1,16/01/2024
1,2,Strength in Struggle,Strength in Struggle\nImage\n\nLife—it's tough...,227,13,16,2,24/01/2024
2,3,付费自习室的兴起，预示着什么?,付费自习室的兴起，预示着什么?\nImage\n\n付费自习室的兴起，预示着什么？\n\nT...,319,10,13,2,31/01/2024
3,4,Focus,Focus\nImage\n\nWere you ever given a task tha...,145,8,7,3,06/02/2024
4,5,Hamilton 汉密尔顿,Hamilton 汉密尔顿\n\n\nHamilton--an epic of freedo...,320,10,12,1,13/02/2024

Right now, text has some words that aren't a part of the article such as images replace by the word "Image".

In [2]:
plrty["Text"]

0     Interview: Struggles in Learning English and H...
1     Strength in Struggle\nImage\n\nLife—it's tough...
2     付费自习室的兴起，预示着什么?\nImage\n\n付费自习室的兴起，预示着什么？\n\nT...
3     Focus\nImage\n\nWere you ever given a task tha...
4     Hamilton 汉密尔顿\n\n\nHamilton--an epic of freedo...
5     Social Anxiety 社交焦虑\nImage\n\nReducing social ...
6     The Catcher in the Rye 麦田里的守望者\nImage\n\nThe C...
7     Learning Through Imitation 在模仿中学习\nImage\n\nHa...
8     Interview: Advice on Career Picking and Prepar...
9     Falling in Love with...Yourself? 爱上...你自己?\nIm...
10    Detachment 超脱\nImage\n\nDetachment is a 2011 A...
11    Is MBTI Scientific? MBTI 科学吗？\nImage\n\nINTJ, ...
12    I Could Define Myself Something About Characte...
13    The Past, Our Bittersweet Reminder\nImage\n\nT...
14    How Teenagers Use the Internet Today\nImage\n\...
15    Interview: Living Abroad\nImage\n\nAre you hes...
16    Polarity: RECRUITING NEW MEMBERS!!!\nImage\n\n...
17    Future is Never Decided by One Moment 未来从不由一刻决...
18    Feminism in the 2024 Olympics: A Milestone for...
19    Living a Thousand Days vs Living One Day a Tho...
20    ABOUT POLARITY (S.Y. 2024-2025) | 社团&成员介绍\nIma...
21    Paradox of Freedom 自由的悖论\nImage\n\nFreedom is ...
22    如何提升人生幸福感 How to Enhance Life Satisfaction\nIm...
23    The Queen of Mystery 推理女王\nImageImage\n\nAgath...
24    Story of Bananas 香蕉的故事\nImage\n\nBeing one of ...
25    影评: 弗兰西斯哈(Frances Ha)\n\n\nFrances, 怀揣着舞蹈梦奔跑跃动...
26    How Different Philosophies Shape You 不同的哲学如何塑造...
27    对于高敏感所带来的问题，我们真的需要一个解决方案吗？\nImage\n\n一个对于外界环境变...
28    Question Everything 质疑一切\nImage\n\nWe all have...
29    Attention 注意力\nImage\n\n在Ulric Neisser, Robert...
30    A Journey to Overcoming Study Anxiety 克服学习焦虑之旅...
31    Thanksgiving: A Season of Gratitude\n\n\nIt’s ...
32    Period "Herstory" － A Red Revolutionary\nImage...
33    December 2024 Book and Movie/Film Recommendati...
34    保存在树脂冰淇凌里的甜蜜回忆\nImage\n\n树脂作为一种多用途的材料，为艺术家们提供了...
35    Greene Kàrroll [连载]\nImageImage\n\nThe room sm...
36    I Love It When It Rains\nImage\n\n    People d...
37    "it don't matter if you’re black or white"\nIm...
38    Envy 羡慕\nImage\n\nIn Chinese, we have an old s...
39    What is Schizophrenia? 精神分裂症是什么？\nImage\n\nEdu...
40    2025: New Year, New Start\nImage\n\nWith only ...
41    January 2025 Book and Movie/Film Recommendatio...
42    玩物丧志吗？Can a Hobby Really Harm Your Success?\nI...
43    Movie Review: Along With the Gods\nImage\n\nAl...
44    不管宇航员再聪明，到了太空都会变笨？\nImage\n\n许多进入太空的宇航员都是地球上最聪...
45    被优绩主义困住的我们 Trapped by Meritocracy\nImage\n\n“你...
46    Life is Soup and I’m a Fork\nImage\n\nLife is ...
47    Sleep and Dreams\nImage\n\nHave you ever had a...
48    恭喜发财，红包拿来！\nImage\n\nAs the Spring Festival ap...
49    February 2025 Book and Movie/Film Recommendati...
Name: Text, dtype: object

Before removing these "Image"s, it is helpful to count how many there are for future analysis. To account for instances where a valid instance of "Image" does not correspond to a picture, we will count the number of "Image"s before and after removing them.

In [3]:
#counts all instances of "Image"
image_before = plrty["Text"].str.count("Image")

#remove "Images" only when in its own line and put cleaned text in a new column
plrty["cleanText"] = (
    plrty["Text"].str.replace(r"(?m)^(?:Image)+(?:\n|$)", "", regex=True)
)

#counts instances of "Image" in the article text
image_after = plrty["cleanText"].str.count("Image")

#add a new column for number of images
plrty["num_images"] = image_before - image_after
print(plrty["num_images"])

0      9
1      3
2      3
3      3
4      3
5      3
6      3
7      3
8      7
9      3
10     3
11     3
12     5
13     4
14     3
15    11
16     5
17     3
18     3
19     3
20     8
21     3
22     3
23     4
24     3
25     2
26     2
27     3
28     3
29     3
30     0
31     4
32     7
33     7
34     9
35     5
36     3
37     7
38     6
39     6
40     6
41     8
42     7
43     8
44     3
45     5
46     6
47     3
48    12
49     8
Name: num_images, dtype: int64

There are some empty lines at the end of some articles

In [4]:
#remove empty lines at the end of article
plrty["cleanText"] = plrty["cleanText"].str.rstrip()

Let's check an article

In [5]:
print(plrty.loc[1, "cleanText"])

Strength in Struggle

Life—it's tough, draining, and a shared experience for us all. Many wake up and fall asleep with troubled thoughts and heavy hearts, grappling with struggles in school, family, friendships, or love. These hardships might seem like they drag us down, hindering our progress. But is that really the case? Do the hardships we face tear us apart and thwart our goals? No. Seriously, no. While most would argue against it, consider this: Can you achieve greatness without hardships and effort? And would it still be fulfilling to achieve something without lifting your finger? Absolutely not, so reconsider.



生活——对我们所有人来说都是艰难的，令人筋疲力尽的。许多人入睡时都带着烦恼的想法和沉重的心情，醒来时亦是如此，在学校、家庭、友谊或爱情中挣扎。这些困难看起来似乎是我们的累赘，但事实真是如此吗？我们面临的困难是否会使我们粉身碎骨，并最终阻碍我们实现梦想？不，说真的，并非如此。虽然大多数人会下意识地反对这一点，但请考虑一下：不经历困难和努力，你能取得伟大成就吗？不费吹灰之力就能实现的某些目标能让你有成就感吗？显然不行，所以，请重新思考一下这些煎熬的意义。



In life, the battles we conquer and endure are countless and will likely remain endless. Should we really allow these obstacles stop us from reaching our goals? Do we really have to give up?



在生活中，我们承受并踏平了无数场战斗，而它们很有可能永远不会终结。那么，我们难道要让这些障碍成为我们与最终的目标之间的高墙吗？我们真的会选择放弃吗？



I’d say giving up should never be an option. Taking a moment to pause, rest, and heal ourselves is the better choice. It's okay to take a break, to run away, and turn a blind eye. After all, we're only human. But when the time comes, when you're ready, please come back, wake up, open your eyes, and welcome the battle in front of you. You're not alone. Everyone else is on this journey.



我想，放弃永远不应该是一种选择。花点时间停下来、歇一会、治愈自己是更好的选择。即使是逃避般地闭上双眼也没关系。毕竟，我们只是人类。但当时机来临，而你准备好了，请回到现实，从美梦中醒来，睁开你的眼睛，去直面眼前的战斗。要知道你不是一个人，世界上的所有人都在体验着这个过程。



I grew up with hardships; I learned, realized, and matured because of them. 2023 was one of the worst years of my life. Some might consider it an exaggeration, but I can still feel the pain I endured. I felt like a shadow, blankly staring at the stars—barely visible and silently a threat. From family, lovers, friends, and classmates to strangers, I felt lost and distant from everyone. I was like a ghost, wafting through the crowd. My feelings built their own forest, a heart fragile as a faded petal released by time, and memories dreadful as a river filled with tears and sorrow. I have so many things I wanted to tell myself, things I share with you now: Find meaning.



我在苦难中成长——也因为它们而学习到知识、意识到哲理、变得成熟。2023 年是我一生中最糟糕的一年。也许有人会觉得这样说有些夸张，但我仍然能感受到我所承受过的痛苦。 我感觉自己就像一个影子，茫然地凝视着星星——几乎没人能看得见我，而我就在在沉默中构成无声的威胁。从家人、爱人、朋友、同学到陌生人，我在每个人身上都感受到了迷茫和疏离，就像一缕在人群里飘忽不定的魂灵。我心中的情感建立了它们自己的森林，其中有一颗如随着时间凋零的花瓣般脆弱的心，和好像一条充满泪水的河流般悲伤的记忆。我有很多话想告诉当时的自己，现在我分享给你们：去找到意义。



I’m pretty sure many of us are exhausted from sitting and paying attention in class for almost the whole day over the week. Spending our lives devoted to studying, especially away from the warmth of our homes, prompts the question: Is all of this really worth it? Is everything truly deserving of our effort and time? It depends. I believe the most important thing in this world is meaning—for us to move on and work harder, especially for ourselves. So, for me, yes. Studying and working hard is deserving, even if it costs me rivers of tears and centuries of time. I'd still continue because it means feeling proud and satisfied for the effort I've put in (even while enjoying). Working hard, pursuing my dreams, enduring hardships, and striving for the future make my life in school more than just basic exhaustion; but a significant growth day by day. To me, there's meaning in choosing to study in China, specifically in Repton. Because I know, at the end of the day, studying and the hardships it brings will always be worth the struggle.



我相信我们中的许多人都因上学而感到精疲力竭——在整整五天里，几乎每一天都要坐在课堂上拼命集中着注意力。我们将一切奉献给学习，更远离温暖的家，这不禁引发了一个问题：这一切真的值得吗？学校的一切真的值得我们付出努力和时间吗？答案并不绝对。我相信这个世界上最重要的事情就是意义——它们让我们得以继续前进并更加努力，尤其是对我们自己这些个体来说。所以我会说，是的——努力学习和工作是值得的，即使我付出了无数的泪水和漫长的时间，我仍然会继续。因为这意味着我能对自己的疲惫感到自豪和满足。付出努力，忍耐煎熬：我们的校园生活不仅仅是单纯的受累；追求梦想，走向未来：而是日复一日的磨砺与成长。对我来说，选择来中国学习，特别是在这所学校学习是很有意义的。因为我知道，最终学习和它带来的艰辛总是值得的。



Now, I'm outside the world. I've found my meaning once again. My eyes are sparkling, my heart is pounding, I'm running—I feel alive. In this school filled with seemingly dead and broken souls, I'm here, full of life and laughter once again.



现在，我已能抽身至现实之外了——我找到了自己的意义。如今，我的眼睛能映射出光芒，我的心在有力的搏动，我的双腿在坚实土地上自由的奔跑——我感到自己还活着。在这里，在这所似乎满是破碎的灵魂的学校里，我再度感到生机和欢笑溢满了我的心灵。



Written By: Jamila Gapuz

Edited By: William Chen

Translated By: Grace Cai

So far so good. For a deeper analysis, we may want to get data on title length and text length

In [6]:
plrty["titleLength"] = plrty["Title"].str.len()
print(plrty["titleLength"])

0     59
1     20
2     15
3      5
4     13
5     19
6     30
7     33
8     51
9     42
10    13
11    29
12    57
13    34
14    36
15    24
16    35
17    47
18    62
19    57
20    41
21    24
22    42
23    25
24    22
25    21
26    47
27    26
28    24
29    13
30    46
31    35
32    39
33    49
34    14
35    19
36    23
37    42
38     7
39    32
40    25
41    48
42    43
43    33
44    18
45    33
46    27
47    16
48    10
49    49
Name: titleLength, dtype: int64

To analyze the effect on the type of language on the number reads, I classified titles into four categories: Bilingual (English text comes first, EC), Bilingual(Chinese text comes first, CE), English (E), and Chinese(C)

In [7]:
def classify_title(title):
    chinese = next((i for i, char in enumerate(title) if "\u4e00" <= char <= "\u9fff"), None)
    english = next((i for i, char in enumerate(title) if char.isascii() and char.isalpha()), None)
    if chinese is None:
      return "E"
    elif english is None:
      return "C"
    elif english < chinese:
      return "EC"
    else:
      return "CE"

plrty["Title_Language"] = plrty["Title"].apply(classify_title)
print(plrty["Title_Language"])

0      E
1      E
2      C
3      E
4     EC
5     EC
6     EC
7     EC
8      E
9     EC
10    EC
11    EC
12     E
13     E
14     E
15     E
16     E
17    EC
18     E
19     E
20    EC
21    EC
22    CE
23    EC
24    EC
25    CE
26    EC
27     C
28    EC
29    EC
30    EC
31     E
32     E
33     E
34     C
35    EC
36     E
37     E
38    EC
39    EC
40     E
41     E
42    CE
43     E
44     C
45    CE
46     E
47     E
48     C
49     E
Name: Title_Language, dtype: object

In [8]:
#Gets text length
plrty["textLength"] = plrty["cleanText"].str.len()
print(plrty["textLength"])

0     2841
1     4453
2     6755
3     4274
4     5935
5     5317
6     5921
7     4786
8     5336
9     4499
10    7109
11    4853
12    6194
13    4185
14    6955
15    3769
16    1472
17    3667
18    3611
19    4290
20    1706
21    2778
22    2576
23    4167
24    7704
25    3616
26    3804
27    5059
28    4673
29    2581
30    3806
31    5350
32    8456
33    5976
34    2955
35    3897
36    6004
37    4323
38    7513
39    3765
40    5665
41    9753
42    4272
43    7626
44    3824
45    4661
46    3830
47    2991
48    8196
49    9861
Name: textLength, dtype: int64

Finally, our table looks like this

In [9]:
plrty.head()

,id,Title,Text,Reads,Likes,Shares,Hearts,Date Published,cleanText,num_images,titleLength,Title_Language,textLength
0,1,Interview: Struggles in Learning English and H...,Interview: Struggles in Learning English and H...,198,12,10,1,16/01/2024,Interview: Struggles in Learning English and H...,9,59,E,2841
1,2,Strength in Struggle,Strength in Struggle\nImage\n\nLife—it's tough...,227,13,16,2,24/01/2024,"Strength in Struggle\n\nLife—it's tough, drain...",3,20,E,4453
2,3,付费自习室的兴起，预示着什么?,付费自习室的兴起，预示着什么?\nImage\n\n付费自习室的兴起，预示着什么？\n\nT...,319,10,13,2,31/01/2024,付费自习室的兴起，预示着什么?\n\n付费自习室的兴起，预示着什么？\n\nThe Rise...,3,15,C,6755
3,4,Focus,Focus\nImage\n\nWere you ever given a task tha...,145,8,7,3,06/02/2024,Focus\n\nWere you ever given a task that you s...,3,5,E,4274
4,5,Hamilton 汉密尔顿,Hamilton 汉密尔顿\n\n\nHamilton--an epic of freedo...,320,10,12,1,13/02/2024,Hamilton 汉密尔顿\n\n\nHamilton--an epic of freedo...,3,13,EC,5935

In [10]:
plrty.to_csv("Polarity_cleaned_50.csv", index=False)